"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#89b4fa"

[character]
success_symbol = "[❯](#cba6f7)"
error_symbol = "[❯](#f38ba8)"
vimcmd_symbol = "[❮](#a6e3a1)"

[git_branch]
format = "[$branch]($style)"
style = "#a6adc8"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#f5c2e7) ($ahead_behind$stashed)]($style)"
style = "#94e2d5"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#7f849c"

[cmd_duration]
format = "[$duration]($style) "
style = "#f9e2af"

[python]
format = "[$virtualenv]($style) "
style = "#7f849c"
detect_extensions = []
detect_files = []
