;;; haxe-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from haxe-mode.el

(add-to-list 'auto-mode-alist '("\\.hx\\'" . haxe-mode))
(autoload 'haxe-mode "haxe-mode" "\
Major mode for editing Haxe code.

The hook `c-mode-common-hook' is run with no args at mode
initialization, then `haxe-mode-hook'.

Key bindings:
\\{haxe-mode-map}" t)
(register-definition-prefixes "haxe-mode" '("haxe-"))

;;; End of scraped data

(provide 'haxe-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; haxe-mode-autoloads.el ends here
